#!/bin/bash

source "${HOME}/.cache/wal/colors.sh"
# Make upper case and convert to rgb
bg_col=`echo $background | tr '[:lower:]' '[:upper:]'`
back_r=`echo "ibas=16; ${bg_col:1:2}" | bc`
back_g=`echo "ibas=16; ${bg_col:3:2}" | bc`
back_b=`echo "ibas=16; ${bg_col:5:2}" | bc`

sed -i "s/set default-bg *\"$background\"/set default-bg rgba($back_r,$back_g,$back_b,0.8)/g" "${HOME}/.cache/wal/zathurarc"
sed -i "s/set recolor-lightcolor *\"$background\"/set recolor-lightcolor rgba($back_r,$back_g,$back_b,0)/g" "${HOME}/.cache/wal/zathurarc"

mkdir -p  "${HOME}/.config/dunst"
mkdir -p  "${HOME}/.config/zathura"
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"
ln -sf    "${HOME}/.cache/wal/zathurarc"    "${HOME}/.config/zathura/zathurarc"

fix_sequences() {
        e=$'\e'
        sequences=$(cat)
        foreground_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]10[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        background_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]11[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"
        cursor_color="$(echo -e "${sequences}\c" | grep --color=never -Eo "${e}]12[^${e}\\\\]*?${e}\\\\" | grep --color=never -Eo "#[0-9A-Fa-f]{6}")"

for term in /dev/pts/{0..9}*
do
echo -e "\e]4;256;${cursor_color}\a\c" > "${term}" 2>/dev/null
echo -e "\e]4;258;${background_color}\a\c" > "${term}" 2>/dev/null
echo -e "\e]4;259;${foreground_color}\a\c" > "${term}" 2>/dev/null
done
}

fix_sequences <"${HOME}/.cache/wal/sequences"

pkill dunst; dunst &
